# Generated by Django 4.2.7 on 2024-11-05 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
