services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=universe_users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@$$w0rd
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:P@$$w0rd@db:5432/universe_users
      - redis
    volumes:
      - .:/app
